const data = [
  {
    name: "John Doe",
    profileImage: "http://image.png",
    gender: "MALE",
    influencerName: "john.doe",
    influencerType: "Fashion",
    interestedIn: "Clothing",
    minRate: 1000,
    previousBrands: "Nike, Adidas",
    location: "New York",
    bestPosts: "https://instagram.com",
  },
  {
    name: "Jane Doe",
    profileImage: "http://image2.png",
    gender: "FEMALE",
    influencerName: "jane.doe",
    influencerType: "Beauty",
    interestedIn: "Makeup",
    minRate: 1200,
    previousBrands: "Sephora, MAC",
    location: "Los Angeles",
    bestPosts: "https://instagram.com/jane.doe",
  },
  {
    name: "Mike Smith",
    profileImage: "http://image3.png",
    gender: "MALE",
    influencerName: "mike.smith",
    influencerType: "Sports",
    interestedIn: "Fitness",
    minRate: 1500,
    previousBrands: "Under Armour, Gatorade",
    location: "Chicago",
    bestPosts: "https://instagram.com/mike.smith",
  },
  {
    name: "Emma Johnson",
    profileImage: "http://image4.png",
    gender: "FEMALE",
    influencerName: "emma.johnson",
    influencerType: "Travel",
    interestedIn: "Adventure",
    minRate: 2000,
    previousBrands: "Airbnb, Delta Airlines",
    location: "San Francisco",
    bestPosts: "https://instagram.com/emma.johnson",
  },
  {
    name: "John Doe",
    profileImage: "http://image.png",
    gender: "MALE",
    influencerName: "john.doe",
    influencerType: "Fashion",
    interestedIn: "Clothing",
    minRate: 1000,
    previousBrands: "Nike, Adidas",
    location: "New York",
    bestPosts: "https://instagram.com",
  },
  {
    name: "Jane Doe",
    profileImage: "http://image2.png",
    gender: "FEMALE",
    influencerName: "jane.doe",
    influencerType: "Beauty",
    interestedIn: "Makeup",
    minRate: 1200,
    previousBrands: "Sephora, MAC",
    location: "Los Angeles",
    bestPosts: "https://instagram.com/jane.doe",
  },
  {
    name: "Mike Smith",
    profileImage: "http://image3.png",
    gender: "MALE",
    influencerName: "mike.smith",
    influencerType: "Sports",
    interestedIn: "Fitness",
    minRate: 1500,
    previousBrands: "Under Armour, Gatorade",
    location: "Chicago",
    bestPosts: "https://instagram.com/mike.smith",
  },
  {
    name: "Emma Johnson",
    profileImage: "http://image4.png",
    gender: "FEMALE",
    influencerName: "emma.johnson",
    influencerType: "Travel",
    interestedIn: "Adventure",
    minRate: 2000,
    previousBrands: "Airbnb, Delta Airlines",
    location: "San Francisco",
    bestPosts: "https://instagram.com/emma.johnson",
  },
  {
    name: "John Doe",
    profileImage: "http://image.png",
    gender: "MALE",
    influencerName: "john.doe",
    influencerType: "Fashion",
    interestedIn: "Clothing",
    minRate: 1000,
    previousBrands: "Nike, Adidas",
    location: "New York",
    bestPosts: "https://instagram.com",
  },
  {
    name: "Jane Doe",
    profileImage: "http://image2.png",
    gender: "FEMALE",
    influencerName: "jane.doe",
    influencerType: "Beauty",
    interestedIn: "Makeup",
    minRate: 1200,
    previousBrands: "Sephora, MAC",
    location: "Los Angeles",
    bestPosts: "https://instagram.com/jane.doe",
  },
  {
    name: "Mike Smith",
    profileImage: "http://image3.png",
    gender: "MALE",
    influencerName: "mike.smith",
    influencerType: "Sports",
    interestedIn: "Fitness",
    minRate: 1500,
    previousBrands: "Under Armour, Gatorade",
    location: "Chicago",
    bestPosts: "https://instagram.com/mike.smith",
  },
  {
    name: "Emma Johnson",
    profileImage: "http://image4.png",
    gender: "FEMALE",
    influencerName: "emma.johnson",
    influencerType: "Travel",
    interestedIn: "Adventure",
    minRate: 2000,
    previousBrands: "Airbnb, Delta Airlines",
    location: "San Francisco",
    bestPosts: "https://instagram.com/emma.johnson",
  },
  {
    name: "John Doe",
    profileImage: "http://image.png",
    gender: "MALE",
    influencerName: "john.doe",
    influencerType: "Fashion",
    interestedIn: "Clothing",
    minRate: 1000,
    previousBrands: "Nike, Adidas",
    location: "New York",
    bestPosts: "https://instagram.com",
  },
  {
    name: "Jane Doe",
    profileImage: "http://image2.png",
    gender: "FEMALE",
    influencerName: "jane.doe",
    influencerType: "Beauty",
    interestedIn: "Makeup",
    minRate: 1200,
    previousBrands: "Sephora, MAC",
    location: "Los Angeles",
    bestPosts: "https://instagram.com/jane.doe",
  },
  {
    name: "Mike Smith",
    profileImage: "http://image3.png",
    gender: "MALE",
    influencerName: "mike.smith",
    influencerType: "Sports",
    interestedIn: "Fitness",
    minRate: 1500,
    previousBrands: "Under Armour, Gatorade",
    location: "Chicago",
    bestPosts: "https://instagram.com/mike.smith",
  },
  {
    name: "Emma Johnson",
    profileImage: "http://image4.png",
    gender: "FEMALE",
    influencerName: "emma.johnson",
    influencerType: "Travel",
    interestedIn: "Adventure",
    minRate: 2000,
    previousBrands: "Airbnb, Delta Airlines",
    location: "San Francisco",
    bestPosts: "https://instagram.com/emma.johnson",
  },
];

export default data;
